### ISSUE TITLE
[BUG] : Issue with browser compatibility - Firefox v103

### ISSUE THREAD

**Issue by Jothin-kumar** [PritamSarbajna/my-portfolio-website#7]
# About section in chrome
![image](https://user-images.githubusercontent.com/84167612/183608919-229e501f-2c06-4d33-b151-15842461a1cd.png)

# About section in Firefox v103 Ubuntu
![image](https://user-images.githubusercontent.com/84167612/183609125-9774191a-314d-4acd-a05e-84628aa65a61.png)

**Comment by PritamSarbajna** [comment]
Hey @Jothin-kumar want to work on this issue ? then I'll assign you

Also I think you can fix this by changing the unit from `px` to `%` or `rem`
